package com.rexfun.greendaodemo.dao.user;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    private String tc_code;
    private String tc_password;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String tc_code, String tc_password) {
        this.id = id;
        this.tc_code = tc_code;
        this.tc_password = tc_password;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTc_code() {
        return tc_code;
    }

    public void setTc_code(String tc_code) {
        this.tc_code = tc_code;
    }

    public String getTc_password() {
        return tc_password;
    }

    public void setTc_password(String tc_password) {
        this.tc_password = tc_password;
    }

}
